language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.2

before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    linux)
      ant bootstrap
      ;;
    osx)
      brew update
      brew install ant
      ant bootstrap
      ;;
    esac;
