language: java

cache:
  directories:
    - $HOME/travis

jdk:
  - oraclejdk8
  - openjdk10

env:
  - TARGET="dist-optimized"
  - TARGET="test-unit-hardfail
  - TARGET="test-it-hardfail
  - TARGET="test-perf-hardfail -Dtest.coverage=false"

script:
  - travis/run.sh

